{% set name = "trollsift" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f09f37f79027668be36610d4c39c36679cb65d2629368f8ae32c7902161263a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python 3.9
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - six

test:
  imports:
    - trollsift

about:
  home: https://github.com/pytroll/trollsift
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: String parser/formatter for PyTroll packages
  description: Filtering modules used in PyTroll packages
  doc_url: http://trollsift.readthedocs.io
  dev_url: https://github.com/pytroll/trollsift

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
