{% set name = "trollsift" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ba29aa6f99083a581fda8e97498c80d28b355d2d2571d4ca3cbfa037c8422f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - six

test:
  imports:
    - trollsift

about:
  home: https://github.com/pytroll/trollsift
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: String parser/formatter for PyTroll packages
  description: Filtering modules used in PyTroll packages
  doc_url: http://trollsift.readthedocs.io
  dev_url: https://github.com/pytroll/trollsift

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
