{% set name = "trollsift" %}
{% set version = "0.3.2" %}
{% set sha256 = "dc6b1612199e38b7c3b1a75803888a38b69ce46d8bc7808690d7e58de2befc18" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - trollsift

about:
  home: https://github.com/pytroll/trollsift
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: String parser/formatter for PyTroll packages
  description: Filtering modules used in PyTroll packages
  doc_url: http://trollsift.readthedocs.io
  dev_url: https://github.com/pytroll/trollsift

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
