{% set name = "trollsift" %}
{% set version = "0.3.3" %}
{% set sha256 = "53218dee54fe4a107a3c95019839c05fb3ea80832c2476f56d243e19db0aaa6b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - trollsift

about:
  home: https://github.com/pytroll/trollsift
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: String parser/formatter for PyTroll packages
  description: Filtering modules used in PyTroll packages
  doc_url: http://trollsift.readthedocs.io
  dev_url: https://github.com/pytroll/trollsift

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
