travis:
  secure:
    BINSTAR_TOKEN: m8AiMS2+mWF1Iyi6gKQLzi5+x8nvkRqLhWKIdqSKhJlweGIQBZkEKshH0hU3G13hFfYv+TYvjLNU4TkvwEj1vK/nb2b5A44jGG+Z1ueOupKeZEuSEBHWt1Y3BL0Rk/RA003cKMwjnpJVnoEcotqVy6a/1274As/VsRqu3K9LMORk+OgboTi449KS3H6XQ2q5DRHGjDrR23jUo27eSjBNa9Ss6781jundzDpjCiYCVD/LadiZORvk1keCmleu/AH6593oK8wTMizgxLWjWpkeYa9LAeLS2fe4b3GVDz0G1X+O1VqNm0sJa/iAvWM0aAcn8yYfsr5/1Jnl+3soF272FuuByTxMWpZsn4Qoaq3+I2votj+hhfdAz6G3qKlHqbTMHklu9Vs64a7QK7N7tFojOB9ckNb2I49fTBkL0VGAN7KVIpz/I6VHyjqurWtQiAQVj9D1ishS5JSEQDk6beUAD4xaqNsIJ1ZF4ASvhyqqD4g/M9F1tEyXiJJ4YqgsJXcTsbyl7xj6jHiKQtJNAa9EFDxwbltZaQbjGfnVEaSi7k/dMFqB9shQDiyiLoi5tv4QCo4TohsaKqZBPyywNRRZSEAyzdbKJZhY58zBVxfR0bdgHBsHOavOWtbeOm5ylXFbde0VKVu+sqo2Id9WGkQo66WTxAfAwfHaUEAzGEZSD8A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
