travis:
  secure:
    BINSTAR_TOKEN: j7uGZNHUWsWAFdPud46pg1uKxoJvOn4J617ZvtO0ZYbtCFRYpGF/V0iOXHXuF3WiWvuqAELrU7cFUSDr9E2OEZT3Bhdvl3YNiG82cunSRIKEop2MZh7EaAF+PiLIsd+/ZjfaZqSXNLd9fHeeLMtYypveKzjjWzzIlTg/JnxJcQmKdXKjWEkkuwLqALtU+FaNunlwgM43oEyA+kTGyvTeSNxms6S95iNnyvHui8/FBiTBnSHYoYWpPuxEIp01VvVb8SN6r6ra/C12y4Ku1+GnegA/JbPP/Ff7E2GxmA4iHJRAvJc/x6umr5lzq4e/VF6CLh2qfxXVL6DUnx9vnYQTSPPuyQg04BXsQ79vI37kFlx+4VRsFfyzEoYjLtm6Tulr+tip6fiEdv61eu/xnNCMwYfe1loLA/JTDFfGMTdEOxvo2VjoFWKyoKMIWr3nlYnU6b6pDoouB7t5smYKl+OrQoHqr3vpMHFkBJLPHfzr6ugLEFu6uq6iznrpF5AiONTfzN1DV84A3ldmIJEUtv6NGIc1RKmf1hjHRfXH3QxiW0QVLchtgib0UggpxhtwF0M3yERH4OWaTsHK7PQw3yhIm6puaz+c0+mFfqxj9ifsZMsTcj7+Dimg7Rs6TYms+rTYKvJdzVOaP69XnhmXNrAR66aVHDuzfQHr9ozLGeajp5s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
